public enum TokenType {
        NUM, PLUS, MINUS, MUL, DIV, LT, LTE, GT, GTE, OP, CP, NOEQ, EQEQ, EQ, ID, INT, SECOL, OBRA, CBRA, IF, WHILE,
        VOID, AND, OR, PROGRAM, INVALID, PUBLIC, PRIVATE, CLASS, SEMICOLON, ANDAND, OROR, ASSIGN;
    }